# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Mr. Bansal
tagline:             'Programmer | Blogger | Reader | CSM'
description:         'A Front End Developer with Exp of more than 9 years. <a href="https://twitter.com/kapilbansal27" target="_blank">@kapilbansal27</a>.'
url:                 http://kapilbansa27.github.io/devu
baseurl:             ''
paginate:            5

# About/contact
author:
  name:             kapil Bansal
  url:               https://twitter.com/kapilbansal27
  email:             kapilbansal27@gmail.com

# Custom vars
version:             1.0.0

#date
future: true

# Gems
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"


